import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import pptxgen from "pptxgenjs";
import { saveAs } from "file-saver";
import { Campaign, Chapter, Question } from "../types";

export const exportToDocx = async (campaign: Campaign) => {
  const children: any[] = [
    new Paragraph({
      text: campaign.campaignTitle,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  ];

  campaign.chapters.forEach((chapter, cIndex) => {
    children.push(
      new Paragraph({
        text: `Chương ${cIndex + 1}: ${chapter.title}`,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 400, after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Khu vực: ", bold: true }),
          new TextRun(chapter.areaName),
        ],
        spacing: { after: 100 },
      }),
      new Paragraph({
        children: [
          new TextRun({ text: "Quái vật: ", bold: true }),
          new TextRun(chapter.monsterName),
        ],
        spacing: { after: 200 },
      })
    );

    chapter.questions.forEach((q, qIndex) => {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `Câu ${qIndex + 1} (${q.levelName}): `, bold: true }),
            new TextRun(q.question),
          ],
          spacing: { before: 200, after: 100 },
        })
      );

      if (q.type === "multiple_choice" && q.options) {
        q.options.forEach((opt, oIndex) => {
          const letter = String.fromCharCode(65 + oIndex); // A, B, C, D
          children.push(
            new Paragraph({
              text: `${letter}. ${opt}`,
              spacing: { before: 50, after: 50 },
              indent: { left: 720 }, // Indent 0.5 inch
            })
          );
        });
      } else if (q.type === "fill_in_the_blank") {
        children.push(
          new Paragraph({
            text: `Điền vào chỗ trống: ................................................................`,
            spacing: { before: 100, after: 100 },
            indent: { left: 720 },
          })
        );
      } else if (q.type === "essay") {
        children.push(
          new Paragraph({
            text: `Phần làm bài tự luận (Viết vào giấy):`,
            italics: true,
            spacing: { before: 100, after: 100 },
            indent: { left: 720 },
          })
        );
      }
      
      // Answer Key at the end
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: "Đáp án: ", bold: true, color: "FF0000" }),
            new TextRun({ text: q.correctAnswer, color: "FF0000" }),
          ],
          spacing: { before: 100, after: 100 },
          indent: { left: 720 },
        }),
        new Paragraph({
          children: [
            new TextRun({ text: "Giải thích: ", bold: true, italics: true }),
            new TextRun({ text: q.explanation, italics: true }),
          ],
          spacing: { before: 100, after: 200 },
          indent: { left: 720 },
        })
      );
    });
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${campaign.campaignTitle}.docx`);
};


export const exportToPptx = async (campaign: Campaign) => {
  const pptx = new pptxgen();

  // Title Slide
  const slideTitle = pptx.addSlide();
  slideTitle.background = { color: "1E293B" }; // slate-800
  slideTitle.addText(campaign.campaignTitle, {
    x: 1,
    y: 2,
    w: "80%",
    h: 1,
    fontSize: 44,
    bold: true,
    color: "FFFFFF",
    align: "center",
  });
  slideTitle.addText("Generated by QuestMind AI", {
    x: 1,
    y: 3.5,
    w: "80%",
    h: 1,
    fontSize: 24,
    color: "94A3B8", // slate-400
    align: "center",
  });

  campaign.chapters.forEach((chapter, cIndex) => {
    // Chapter Title Slide
    const slideChapter = pptx.addSlide();
    slideChapter.background = { color: "334155" }; // slate-700
    slideChapter.addText(`Chương ${cIndex + 1}: ${chapter.title}`, {
      x: 1,
      y: 1.5,
      w: "80%",
      fontSize: 36,
      bold: true,
      color: "FCD34D", // amber-300
      align: "center",
    });
    slideChapter.addText(`Khu vực: ${chapter.areaName}\nQuái vật: ${chapter.monsterName}`, {
      x: 1,
      y: 3,
      w: "80%",
      fontSize: 24,
      color: "E2E8F0",
      align: "center",
    });

    // Question Slides
    chapter.questions.forEach((q, qIndex) => {
      const slideQ = pptx.addSlide();
      slideQ.background = { color: "0F172A" }; // slate-950

      slideQ.addText(`Câu ${qIndex + 1} (${q.levelName})`, {
        x: 0.5,
        y: 0.5,
        w: "90%",
        fontSize: 28,
        bold: true,
        color: "38BDF8", // sky-400
      });

      slideQ.addText(q.question, {
        x: 0.5,
        y: 1.2,
        w: "90%",
        fontSize: 24,
        color: "FFFFFF",
      });

      if (q.type === "multiple_choice" && q.options) {
        let yOffset = 2.5;
        q.options.forEach((opt, oIndex) => {
          const letter = String.fromCharCode(65 + oIndex); // A, B, C, D
          slideQ.addText(`${letter}. ${opt}`, {
            x: 1.0,
            y: yOffset,
            w: "80%",
            fontSize: 20,
            color: "E2E8F0",
          });
          yOffset += 0.6;
        });
      } else {
        slideQ.addText(q.type === "essay" ? "[Phần tự luận]" : "[Điền vào chỗ trống]", {
          x: 1.0,
          y: 3.0,
          w: "80%",
          fontSize: 22,
          italic: true,
          color: "94A3B8",
        });
      }
      
      // Add answer in the notes
      slideQ.addNotes(`Đáp án: ${q.correctAnswer}\nGiải thích: ${q.explanation}`);
    });
  });

  await pptx.writeFile({ fileName: `${campaign.campaignTitle}.pptx` });
};
